development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: trees
  pool: 5
  username: root
  password:
  host: localhost
  socket: /Applications/XAMPP/xamppfiles/var/mysql/mysql.sock

