# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62a8c69adccc3816615a7eedd73070e53957e0dccd7d487d0d83b9accee57b2b5e38280d5f4a2c06644074a5ee5544fa05667114fbe834711eedeaebe0eeb8b6

test:
  secret_key_base: c95b4c6d355a8edc4ce480dc1bd9e40a1225893c2c9db183c02217e844dc8d4fe8ffd091921f3f4768f90f1e6eb39e215e8248207310c725357736c6607b9f76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
